/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package supplierInvoice;

import de.javasoft.plaf.synthetica.SyntheticaBlueMoonLookAndFeel;
import grn.Grn;
import grn.GrnForm;
import grn.GrnUtilities;
import grn.ValidationGRN;
import item.Item;
import item.ItemForm;
import item.ItemUtilities;
import item.ValidationItem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import randimaexporters.MainMenu;
import supplier.Supplier;
import supplier.SupplierForm;
import supplier.SupplierUtilities;
import supplierPayment.CashForm;

/**
 *
 * @author PC
 */
public class MakeGrn extends javax.swing.JDialog {

    int qty;
    int newQtyOnHand;
    int qtyOnHand;
    
    private MainMenu mm = null;

    /**
     * Creates new form MakeGrn
     */
    public MakeGrn(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        ImageIcon icon = new ImageIcon(getClass().getResource("/buyer/Untitled-4.jpg"));

        jXImagePanel1.setImage(icon.getImage());

        javax.swing.Timer timer = new javax.swing.Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();

                SimpleDateFormat format1 = new SimpleDateFormat("hh : mm : ss");
                String dateString = format1.format(date);
                timeLabel.setText(dateString);
            }
        });
        timer.start();

        Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String date = formatter.format(currentDate.getTime());
        dateLabel.setText(date);

        Utility uId = new Utility();

        uId.descriptionComboItem(itemComboBox, "Select Description from Item");
        uId.descriptionComboSupId(supIdComboBox, "Select supId from Supplier");
        uId.descriptionComboSupName(supNameComboBox, "Select supName from Supplier");

        ComboUtil cuId = new ComboUtil();
        cuId.setSearchableCombo(supIdComboBox, true, "No Supplier");
        cuId.setSearchableComboName(supNameComboBox, true, "No Supplier");
        cuId.setSearchableComboItem(itemComboBox, true, "No Item");

        String s = new String(Utility.getNextId("grnId", "GRN", "RECCS"));
        invoiceText.setText(s);
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        invoiceText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        addressText = new javax.swing.JTextField();
        supIdComboBox = new javax.swing.JComboBox();
        supNameComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        itemComboBox = new javax.swing.JComboBox();
        qtyText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        fullAmountText = new javax.swing.JTextField();
        dataBaseButton = new javax.swing.JButton();
        payButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jXImagePanel1 = new org.jdesktop.swingx.JXImagePanel();
        invoiceButton = new javax.swing.JButton();
        addItemButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 236, 245));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Make GRN"));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Make GRN");

        jLabel6.setText("Invoice No :-");

        addButton.setText("Add New Supplier");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        supIdComboBox.setEditable(true);
        supIdComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        supIdComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supIdComboBoxActionPerformed(evt);
            }
        });
        supIdComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supIdComboBoxKeyReleased(evt);
            }
        });

        supNameComboBox.setEditable(true);
        supNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        supNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supNameComboBoxActionPerformed(evt);
            }
        });
        supNameComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                supNameComboBoxKeyPressed(evt);
            }
        });

        jLabel2.setText("Supplier ID");

        jLabel3.setText("Supplier Name");

        jLabel4.setText("Address");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Description", "Qty", "Tare", "Unit Price", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable);

        jLabel7.setText("Select Item");

        jLabel9.setText("Qty");

        itemComboBox.setEditable(true);
        itemComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        itemComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemComboBoxActionPerformed(evt);
            }
        });

        qtyText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyTextActionPerformed(evt);
            }
        });
        qtyText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyTextKeyPressed(evt);
            }
        });

        jLabel10.setText("Full Amount");

        fullAmountText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        dataBaseButton.setText("Add to DataBase");
        dataBaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataBaseButtonActionPerformed(evt);
            }
        });

        payButton.setText("Pay");
        payButton.setEnabled(false);
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXImagePanel1Layout = new javax.swing.GroupLayout(jXImagePanel1);
        jXImagePanel1.setLayout(jXImagePanel1Layout);
        jXImagePanel1Layout.setHorizontalGroup(
            jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        jXImagePanel1Layout.setVerticalGroup(
            jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        invoiceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buyer/8.jpg"))); // NOI18N
        invoiceButton.setBorderPainted(false);
        invoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceButtonActionPerformed(evt);
            }
        });

        addItemButton.setText("Add Item");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buyer/7.jpg"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addItemButton)
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(itemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qtyText, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(invoiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fullAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dataBaseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(payButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(supNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(supIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(invoiceText))
                            .addComponent(jXImagePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButton)
                        .addGap(10, 10, 10)))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXImagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(supIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(invoiceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(supNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(itemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addItemButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fullAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(payButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dataBaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(invoiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        SupplierForm sf = new SupplierForm(null, true);
        
        String s = new String(Utility.getNextPaymentId("supId", "Supplier", "RE-SP-S"));
        sf.idText.setText(s);
        
        sf.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void supIdComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supIdComboBoxActionPerformed
        // TODO add your handling code here:
        String id = (String) (supIdComboBox.getSelectedItem());
        Supplier s = null;
        try {
            s = SupplierUtilities.searchSupplier(id);
        } catch (SQLException e) {
        }

        try {
            supNameComboBox.setSelectedItem(s.getSupName());
            addressText.setText(s.getAddress());
        } catch (NullPointerException nm) {
        }
    }//GEN-LAST:event_supIdComboBoxActionPerformed

    private void supIdComboBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supIdComboBoxKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_supIdComboBoxKeyReleased

    private void supNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supNameComboBoxActionPerformed
        String name = (String) (supNameComboBox.getSelectedItem());
        Supplier s = null;
        try {
            s = SupplierUtilities.searchSupplierName(name);
        } catch (SQLException e) {
        }
        try {
            supIdComboBox.setSelectedItem(s.getSupId());
            addressText.setText(s.getAddress());
        } catch (NullPointerException nm) {
        }
    }//GEN-LAST:event_supNameComboBoxActionPerformed

    private void supNameComboBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supNameComboBoxKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_supNameComboBoxKeyPressed

    private void itemComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemComboBoxActionPerformed

        String description = (String) (itemComboBox.getSelectedItem());
        Item i = null;
        try {
            i = ItemUtilities.searchDescription(description);
        } catch (SQLException e) {
        }
        try {
            qtyOnHand = i.getQty();
        } catch (NullPointerException nm) {
        }


    }//GEN-LAST:event_itemComboBoxActionPerformed

    private void qtyTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTextKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            try {
                qty = Integer.parseInt(qtyText.getText());

                String description = (String) (itemComboBox.getSelectedItem());

                Item i = null;

                try {
                    i = ItemUtilities.searchDescription(description);

                    Object data[] = new Object[6];

                    data[0] = i.getItemcode();
                    data[1] = description;
                    data[2] = qty;
                    data[3] = qty * (double) 3 / 100;
                    data[4] = i.getUnitPrice();
                    data[5] = i.getUnitPrice() * qty * (double) 97 / 100;

                    ((DefaultTableModel) jTable.getModel()).addRow(data);

                    qtyText.setText("");
                    int row_count = jTable.getRowCount();

                    double total = 0.0;

                    for (int k = 0; k < row_count; k++) {
                        Double amount_at_this_row = (Double) (jTable.getValueAt(k, 5));
                        total += amount_at_this_row;
                    }
                    fullAmountText.setText("" + total);

                    newQtyOnHand = qtyOnHand + qty;

                    //qtyOnHandText.setText("" + newQtyOnHand);


                } catch (SQLException ex) {
                    //Logger.getLogger(AddOrderForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (NumberFormatException nm) {
            }

        }
    }//GEN-LAST:event_qtyTextKeyPressed

    private void dataBaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataBaseButtonActionPerformed

        //add to grn

        String id = invoiceText.getText();
        System.out.println(id);
        double amount = 0;
        String supId = (String) supIdComboBox.getSelectedItem();
        String grnDate = dateLabel.getText();
        DateFormat formatter;
        java.util.Date date = null;
        formatter = new SimpleDateFormat("yyyy-MM-dd");
        try {
            java.util.Date dt = formatter.parse(grnDate);
            date = new java.sql.Date(dt.getTime());

        } catch (ParseException ex) {
            //ex.printStackTrace();
        }

        try {
            amount = Double.parseDouble(fullAmountText.getText());
        } catch (NumberFormatException nm) {
        }
        Grn grn = new Grn(id, supId, date, amount);

        try {
            Object[] options = {"Yes", "No", "Cancel"};
            int res = JOptionPane.showOptionDialog(null, "Do you want to save the changes to GRN?", "Add GRN", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);

            if (res == JOptionPane.YES_OPTION) {
                if (GrnUtilities.addsearchGrn(id) == null) {
                    if (ValidationGRN.isValidGrnId(id) && ValidationGRN.isValidSupId(supId) && ValidationGRN.isValidDate(grnDate) && ValidationGRN.isValidAmount(fullAmountText.getText())) {

                        int rows = GrnUtilities.addGrn(grn);
                        if (rows > 0) {
                            JOptionPane.showMessageDialog(MakeGrn.this, "Successfully Addedd.");
                            payButton.setEnabled(true);
                        }

                    } else if (!ValidationGRN.isValidGrnId(id)) {
                        JOptionPane.showMessageDialog(this, "Please Enter the Corret GRN ID...");
                    } else if (!ValidationGRN.isValidSupId(supId)) {
                        JOptionPane.showMessageDialog(this, "Please Enter the Corret Supplier ID...");
                    } else if (!ValidationGRN.isValidDate(grnDate)) {
                        JOptionPane.showMessageDialog(this, "Please Enter the Corret Date...");
                    } else if (!ValidationGRN.isValidAmount(fullAmountText.getText())) {
                        JOptionPane.showMessageDialog(this, "Please Enter the Corret Amount...");
                    } else {
                        JOptionPane.showMessageDialog(this, "Please Enter the Corret Data...");
                    }
                } else {
                    JOptionPane.showMessageDialog(MakeGrn.this, "The GRN ID you have entered is in the Database...");
                }

            }


        } catch (SQLException ex) {
            Logger.getLogger(GrnForm.class.getName()).log(Level.SEVERE, null, ex);
        }


        //update Item

        int qty = 0;
        String description = (String) (itemComboBox.getSelectedItem());

        try {
            qty = newQtyOnHand;

        } catch (NumberFormatException nm) {
        }

        Item item = new Item(description, qty);

        try {

            Object[] options = {"Yes", "No", "Cancel"};
            int res = JOptionPane.showOptionDialog(null, "Do you want to save the changes to Item?", "Update Item", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);

            if (res == JOptionPane.YES_OPTION) {

                if (ValidationItem.isValidDescription(description) && ValidationItem.isValidQty(String.valueOf(newQtyOnHand))) {

                    int rows = ItemUtilities.updateItem(description, qty);
                    if (rows > 0) {
                        JOptionPane.showMessageDialog(MakeGrn.this, "Update successfully");
                    } else {
                        JOptionPane.showMessageDialog(MakeGrn.this, "No such Item : ");
                    }

                } else {
                    JOptionPane.showMessageDialog(MakeGrn.this, "The data already entered wrong.");
                }

            }


        } catch (SQLException e) {
            JOptionPane.showMessageDialog(MakeGrn.this, "Wrong SQL");
            //e.printStackTrace();
        }

    }//GEN-LAST:event_dataBaseButtonActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        String id = fullAmountText.getText();
        CashForm cForm = new CashForm(null, true);
        
        String s = new String(Utility.getNextPaymentId("paymentId", "SupplierPayment", "RE-GRN-"));
        cForm.paymentIdText.setText(s);
        CashForm.fAmountText.setText(id);
        cForm.grnIdText.setText(invoiceText.getText());
        cForm.setVisible(true);
    }//GEN-LAST:event_payButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "Do you want to Exit ?");
        if (res == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void invoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceButtonActionPerformed
        Invoice in = new Invoice(null, true);
        TableModel t = jTable.getModel();

        in.dataTable.setModel(t);

        //set amount

        String amount = fullAmountText.getText();
        in.amountText.setText(amount);

//        //set Name , Address

        String name = (String) supNameComboBox.getSelectedItem();
        in.nameText.setText(name);
        String country = addressText.getText();
        in.addressText.setText(country);

        //set invoiceId & containerNo

        String invoice = invoiceText.getText();
        in.invoiceLabel.setText(invoice);

        //set date

        String date = dateLabel.getText();
        in.dateLabel.setText(date);

        in.setVisible(true);
    }//GEN-LAST:event_invoiceButtonActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        new ItemForm(null, true).setVisible(true);
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void qtyTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyTextActionPerformed
        String getQty = qtyText.getText();
        String st = getQty.substring(0, getQty.length());
        char[] digit = st.toCharArray();
        for (char ch : digit) {
            if (Character.isDigit(ch)) {
                qtyText.setText(getQty);
            } else {
                qtyText.setText("");
            }
        }
    }//GEN-LAST:event_qtyTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MakeGrn.this.setVisible(false);

        if (mm == null) {
            mm = new MainMenu();
            mm.setVisible(true);
        } else {
            mm.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int res = JOptionPane.showConfirmDialog(this, "Do you want to Exit ?");
        if (res == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeGrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeGrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeGrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeGrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    try {
                        UIManager.setLookAndFeel(new SyntheticaBlueMoonLookAndFeel());
                    } catch (ParseException ex) {
                        Logger.getLogger(MakeGrn.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MakeGrn.class.getName()).log(Level.SEVERE, null, ex);
                }
                MakeGrn dialog = new MakeGrn(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addItemButton;
    private javax.swing.JTextField addressText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton dataBaseButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField fullAmountText;
    private javax.swing.JButton invoiceButton;
    private javax.swing.JTextField invoiceText;
    private javax.swing.JComboBox itemComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable;
    private org.jdesktop.swingx.JXImagePanel jXImagePanel1;
    private javax.swing.JButton payButton;
    private javax.swing.JTextField qtyText;
    private javax.swing.JComboBox supIdComboBox;
    private javax.swing.JComboBox supNameComboBox;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
