/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package buyerPayment;

import de.javasoft.plaf.synthetica.SyntheticaBlueIceLookAndFeel;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import randimaexporters.MainMenu;
import validation.Validator;

/**
 *
 * @author PC
 */
public class CashForm extends javax.swing.JDialog {

    Validator validator;
    ChequeForm cf;
    private MainMenu mm = null;

    /**
     * Creates new form CashForm
     */
    public CashForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        CashUtilities.viewCash(jTable1, "select * from BuyerPayment");

        ImageIcon icon = new ImageIcon(getClass().getResource("/buyer/Untitled-4.jpg"));
        jXImagePanel1.setImage(icon.getImage());

        validator = new Validator();
        validator.setBounds(0, 0, getWidth(), getHeight());
        JLayeredPane pane = getRootPane().getLayeredPane();
        pane.add(validator, JLayeredPane.DEFAULT_LAYER + 500);
        
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        searchText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        paymentIdText = new javax.swing.JTextField();
        payDateText = new javax.swing.JTextField();
        orderIdText = new javax.swing.JTextField();
        amountText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cashCheckBox = new javax.swing.JCheckBox();
        chequeCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        fAmountText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jXImagePanel1 = new org.jdesktop.swingx.JXImagePanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(198, 236, 236));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cash"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Commands"));

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buyer/5.jpg"))); // NOI18N
        addButton.setText("    Add ");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buyer/4.jpg"))); // NOI18N
        editButton.setText("   Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buyer/6.jpg"))); // NOI18N
        deleteButton.setText("   Delete ");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buyer/1.jpg"))); // NOI18N
        clearButton.setText("   Clear ");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buyer/2.jpg"))); // NOI18N
        refreshButton.setText("   Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshButton)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        searchText.setText("Search...");
        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buyer/3.jpg"))); // NOI18N
        searchButton.setBorderPainted(false);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(searchText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cash Information"));

        paymentIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentIdTextActionPerformed(evt);
            }
        });

        payDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payDateTextActionPerformed(evt);
            }
        });

        orderIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderIdTextActionPerformed(evt);
            }
        });

        amountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextActionPerformed(evt);
            }
        });

        jLabel1.setText("Payment ID");

        jLabel3.setText("OrderID");

        jLabel10.setText("Pay Date");

        jLabel11.setText("Amount");

        cashCheckBox.setText("Cash");
        cashCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashCheckBoxActionPerformed(evt);
            }
        });

        chequeCheckBox.setText("Cheque");
        chequeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequeCheckBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Order Full Amount");

        fAmountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fAmountTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cashCheckBox)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderIdText, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(chequeCheckBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(payDateText)
                            .addComponent(amountText)
                            .addComponent(fAmountText)
                            .addComponent(paymentIdText)))
                    .addComponent(jLabel2))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(paymentIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(orderIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(payDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashCheckBox)
                    .addComponent(chequeCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Preview"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment ID", "Order ID", "Pay Date", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel13.setText("Search");

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel14.setText("Cash Information");

        javax.swing.GroupLayout jXImagePanel1Layout = new javax.swing.GroupLayout(jXImagePanel1);
        jXImagePanel1.setLayout(jXImagePanel1Layout);
        jXImagePanel1Layout.setHorizontalGroup(
            jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        jXImagePanel1Layout.setVerticalGroup(
            jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buyer/7.jpg"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buyer/8.jpg"))); // NOI18N
        jButton2.setBorderPainted(false);

        jLabel4.setFont(new java.awt.Font("GIST-TMOTKamal", 3, 24)); // NOI18N
        jLabel4.setText("Buyer Cash Payment");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(128, 128, 128)
                .addComponent(jXImagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXImagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        String id = paymentIdText.getText();
        String orderId = orderIdText.getText();
        double amount = 0;
        String payDate = payDateText.getText();
        DateFormat formatter;
        java.util.Date date = null;
        formatter = new SimpleDateFormat("yyyy-MM-dd");
        try {
            java.util.Date dt = formatter.parse(payDate);
            date = new java.sql.Date(dt.getTime());

        } catch (ParseException ex) {
            //ex.printStackTrace();
        }

        try {
            amount = Double.parseDouble(amountText.getText());
        } catch (NumberFormatException nm) {
        }

        Cash cash = new Cash(id, orderId, date, amount);

        try {
            if (CashUtilities.addsearchcash(id) == null) {
                if (ValidationPayment.isValidPaymentId(id) && ValidationPayment.isValidAmount(amountText.getText()) && ValidationPayment.isValidOrderId(orderId) && ValidationPayment.isValidDate(payDate)) {

                    int rows = CashUtilities.addCash(cash);
                    if (rows > 0) {
                        JOptionPane.showMessageDialog(CashForm.this, "Successfully Addedd.");
                    }
                } else if (!ValidationPayment.isValidPaymentId(id)) {
                    validator.addWarning(paymentIdText);
                    paymentIdText.setText("");
                } else if (!ValidationPayment.isValidAmount(amountText.getText())) {
                    validator.addWarning(amountText);
                    amountText.setText("");
                } else if (!ValidationPayment.isValidOrderId(orderId)) {
                    validator.addWarning(orderIdText);
                    orderIdText.setText("");
                } else if (!ValidationPayment.isValidDate(payDate)) {
                    validator.addWarning(payDateText);
                    payDateText.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong Input...");
                }
            } else {
                validator.addWarning(paymentIdText);
                JOptionPane.showMessageDialog(CashForm.this, "The Payment ID you have entered is in the Database...");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(CashForm.this, "Added Fail.");
            //ex.printStackTrace();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        String id = paymentIdText.getText();
        String orderId = orderIdText.getText();
        double amount = 0;
        String payDate = payDateText.getText();
        DateFormat formatter;
        java.util.Date date = null;
        formatter = new SimpleDateFormat("yyyy-MM-dd");
        try {
            java.util.Date dt = formatter.parse(payDate);
            date = new java.sql.Date(dt.getTime());

        } catch (ParseException ex) {
            //ex.printStackTrace();
        }

        try {
            amount = Double.parseDouble(amountText.getText());
        } catch (NumberFormatException nm) {
        }

        Cash cash = new Cash(id, orderId, date, amount);

        try {

            Object[] options = {"Yes", "No", "Cancel"};
            int res = JOptionPane.showOptionDialog(null, "Do you want to save the changes to Payment?", "Update Payment", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);

            if (res == JOptionPane.YES_OPTION) {
                if (CashUtilities.addsearchcash(id) != null) {
                    if (ValidationPayment.isValidPaymentId(id) && ValidationPayment.isValidAmount(amountText.getText()) && ValidationPayment.isValidOrderId(orderId) && ValidationPayment.isValidDate(payDate)) {

                        int rows = CashUtilities.updateCash(cash);

                        if (rows > 0) {
                            JOptionPane.showMessageDialog(CashForm.this, "Update successfully");
                        } else {
                            JOptionPane.showMessageDialog(CashForm.this, "No such Payment : " + id);
                        }

                    } else if (!ValidationPayment.isValidPaymentId(id)) {
                        validator.addWarning(paymentIdText);
                        paymentIdText.setText("");
                    } else if (!ValidationPayment.isValidAmount(amountText.getText())) {
                        validator.addWarning(amountText);
                        amountText.setText("");
                    } else if (!ValidationPayment.isValidOrderId(orderId)) {
                        validator.addWarning(orderIdText);
                        orderIdText.setText("");
                    } else if (!ValidationPayment.isValidDate(payDate)) {
                        validator.addWarning(payDateText);
                        payDateText.setText("");
                    } else {
                        JOptionPane.showMessageDialog(this, "Wrong Input...");
                    }
                } else {
                    validator.addWarning(paymentIdText);
                    JOptionPane.showMessageDialog(CashForm.this, "The Payment ID you have entered is not in the Database...");
                }

            }
            if (res == JOptionPane.NO_OPTION) {

                CashForm.this.setVisible(false);

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(CashForm.this, "Wrong SQL");
            //e.printStackTrace();
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

        String id = paymentIdText.getText();
        Cash cash = new Cash(id);

        try {

            Object[] options = {"Yes", "No", "Cancel"};
            int option = JOptionPane.showOptionDialog(null, "Are you sure you want to permanently delete this Payment?", "Delete Payment", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);

            if (option == JOptionPane.YES_OPTION) {

                int rows = CashUtilities.deleteCash(cash);
                if (rows > 0) {
                    JOptionPane.showMessageDialog(CashForm.this, "Deleted successfully");
                } else {
                    JOptionPane.showMessageDialog(CashForm.this, "No such Payment : " + id);
                }
            }

            if (option == JOptionPane.NO_OPTION) {

                CashForm.this.setVisible(false);

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(CashForm.this, "Wrong SQL");
            //e.printStackTrace();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed

        validator.removeWarning(paymentIdText);
        validator.removeWarning(orderIdText);
        validator.removeWarning(payDateText);
        validator.removeWarning(amountText);

        paymentIdText.setText("");
        orderIdText.setText("");
        payDateText.setText("");
        amountText.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed

        jTable1.clearSelection();
        int row_count = jTable1.getRowCount();

        for (int i = 0; i < row_count; i++) {

            ((DefaultTableModel) jTable1.getModel()).removeRow(0);

        }
        CashUtilities.viewCash(jTable1, "select * from BuyerPayment");
        
        validator.removeWarning(paymentIdText);
        validator.removeWarning(orderIdText);
        validator.removeWarning(payDateText);
        validator.removeWarning(amountText);

//        Calendar currentDate = Calendar.getInstance();
//        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
//        String date = formatter.format(currentDate.getTime());
//        orderDateText.setText(date);
//        if (evt.getSource() == addButton) {
//        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String search = searchText.getText();

        try {

            Cash cash = CashUtilities.searchCash(search);

            if (cash != null) {
                paymentIdText.setText(search);
                orderIdText.setText(cash.getOrderId());
                payDateText.setText(cash.getPayDate() + "");
                amountText.setText(cash.getAmount() + "");

            } else {
                JOptionPane.showMessageDialog(CashForm.this, "No Such Payment ID :" + search);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(CashForm.this, "Wrong sql");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed

        if (searchText.getText().isEmpty()) {
            searchText.setText("Search...");
        }
        String search = searchText.getText();

        try {

            Cash cash = CashUtilities.searchCash(search);

            if (cash != null) {
                paymentIdText.setText(search);
                orderIdText.setText(cash.getOrderId());
                payDateText.setText(cash.getPayDate() + "");
                amountText.setText(cash.getAmount() + "");

            } else {
                JOptionPane.showMessageDialog(CashForm.this, "No Such Payment ID :" + search);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(CashForm.this, "Wrong sql");
        }
    }//GEN-LAST:event_searchTextActionPerformed

    private void cashCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashCheckBoxActionPerformed

    private void chequeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequeCheckBoxActionPerformed

        String id = paymentIdText.getText();
        ChequeForm chequeForm1 = new ChequeForm(null, true);
        chequeForm1.idText.setText(id);
        if (!id.isEmpty()) {
            chequeForm1.setVisible(true);
        }

    }//GEN-LAST:event_chequeCheckBoxActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(CashForm.this, "non selected row");
        }
        if (selectedRow != -1) {

            String id = (String) jTable1.getValueAt(selectedRow, 1);
            // JOptionPane.showMessageDialog(Form.this, "selected value :" + id);

            try {

                Cash cash = CashUtilities.searchCash(id);

                if (cash != null) {
                    paymentIdText.setText(cash.getPaymentId());
                    orderIdText.setText(cash.getOrderId());
                    payDateText.setText("" + cash.getPayDate());
                    amountText.setText(cash.getAmount() + "");

                } else {
                    System.out.println("cbvvcbnv");
                    JOptionPane.showMessageDialog(CashForm.this, "No Such Payment ID :" + id);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(CashForm.this, "Wrong sql");
            }
        }
        
        validator.removeWarning(paymentIdText);
        validator.removeWarning(orderIdText);
        validator.removeWarning(payDateText);
        validator.removeWarning(amountText);
    }//GEN-LAST:event_jTable1MouseClicked

    private void paymentIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentIdTextActionPerformed
        String id = paymentIdText.getText();
        if (!ValidationPayment.isValidPaymentId(id)) {
            validator.addWarning(paymentIdText);
            paymentIdText.setText("");
        } else {
            orderIdText.requestFocus();
            validator.removeWarning(paymentIdText);
        }
    }//GEN-LAST:event_paymentIdTextActionPerformed

    private void orderIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIdTextActionPerformed
        String id = orderIdText.getText();
        if (!ValidationPayment.isValidOrderId(id)) {
            validator.addWarning(orderIdText);
            orderIdText.setText("");
        } else {
            payDateText.requestFocus();
            validator.removeWarning(orderIdText);
        }
    }//GEN-LAST:event_orderIdTextActionPerformed

    private void payDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payDateTextActionPerformed
        String date = payDateText.getText();
        if (!ValidationPayment.isValidDate(date)) {
            validator.addWarning(payDateText);
            payDateText.setText("");
        } else {
            amountText.requestFocus();
            validator.removeWarning(payDateText);
        }
    }//GEN-LAST:event_payDateTextActionPerformed

    private void amountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextActionPerformed
        String amount = amountText.getText();
        if (!ValidationPayment.isValidAmount(amount)) {
            validator.addWarning(amountText);
            amountText.setText("");
        } else {
            fAmountText.requestFocus();
            validator.removeWarning(amountText);
        }
    }//GEN-LAST:event_amountTextActionPerformed

    private void fAmountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fAmountTextActionPerformed
        String fullAmount = fAmountText.getText();
        if (!ValidationPayment.isValidAmount(fullAmount)) {
            validator.addWarning(fAmountText);
            fAmountText.setText("");
        } else {
            validator.removeWarning(fAmountText);
        }
    }//GEN-LAST:event_fAmountTextActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int res = JOptionPane.showConfirmDialog(this, "Do you want to Exit ?");
        if (res == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       CashForm.this.setVisible(false);
        
        if (mm == null) {
            mm = new MainMenu();
            mm.setVisible(true);
        } else {
            mm.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    try {
                        UIManager.setLookAndFeel(new SyntheticaBlueIceLookAndFeel());
                    } catch (ParseException ex) {
                        Logger.getLogger(CashForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(CashForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                CashForm dialog = new CashForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField amountText;
    private javax.swing.JCheckBox cashCheckBox;
    private javax.swing.JCheckBox chequeCheckBox;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    public static javax.swing.JTextField fAmountText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXImagePanel jXImagePanel1;
    public javax.swing.JTextField orderIdText;
    private javax.swing.JTextField payDateText;
    public static javax.swing.JTextField paymentIdText;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchText;
    // End of variables declaration//GEN-END:variables
}
